export const UNITS = {
  "G215": "Olot",
  "G450": "Olot",
  "G451": "Olot",
  "G452": "Campdevànol",
  "G453": "Camprodon",
  "G413": "Banyoles",
  "G305": "Sant Joan de les Abadesses"
};
export const SUPERVISIONS = {
  'Blanes': { 'SUPERVISOR_BLANES': 'Material supervisor' },
  'Figueres': { 'SUPERVISOR_FIGUERES': 'Material supervisor' },
  'Girona': { 'SUPERVISOR_GIRONA': 'Material supervisor' },
  'Olot': { ...UNITS, 'SUPERVISOR_OLOT': 'Material supervisor' }
};

export const MATERIALS = [
  "Bolsa recambio lsu",
  "Conector de vacio lsu",
  "Tubo silicona lsu",
  "Sonda aspiración yankauer",
  "Sonda aspiración 6",
  "Sonda aspiración 8",
  "Sonda aspiración 10",
  "Sonda aspiración 12",
  "Sonda aspiración 14",
  "Sonda aspiración 16",
  "Sonda aspiración 18",
  "Conexión en y",
  "Parches schiller adulto",
  "Parches schiller pediátrico",
  "Parches monitorización schiller",
  "Cable ecg 4 derivadas",
  "Cable ecg 12 derivadas",
  "Sensor pulsioximetria adulto",
  "Manguito ta pediátrico schiller",
  "Manguito ta adulto schiller",
  "Manguito ta obeso schiller",
  "Parches dea tsnu",
  "Empapador",
  "Pañuelos papel",
  "Kit de partos",
  "Tensiometro digital",
  "Tensiometro infrarojos",
  "Manguito tensiometro infantil",
  "Equipo infusor de suero",
  "Detector de monoxido",
  "Mascarilla ambu 0",
  "Mascarilla ambu 0a",
  "Mascarilla ambu 2",
  "Mascarilla ambu 3/4",
  "Mascarilla ambu 5",
  "Mascarilla ambu 6",
  "Filtro ambu",
  "Válvula peep",
  "Rasuradora",
  "Kit quemados",
  "Mascarilla fpp2",
  "Mascarilla fpp3",
  "Mascarilla quirurgica",
  "Collarin adulto",
  "Collarin pediátrico",
  "Faja pélvica",
  "Inmobilizador hombro",
  "Hierro kramer",
  "Funda kramer",
  "Ferula maleable braquial",
  "Ferula maleable digital",
  "Cánula guedel 00",
  "Cánula guedel 0",
  "Cánula guedel 1",
  "Cánula guedel 1,5",
  "Cánula guedel 2",
  "Cánula guedel 3",
  "Cánula guedel 4",
  "Cánula guedel 5",
  "Mascarilla oxígeno adulta",
  "Mascarilla monaghan adulta",
  "Mascarilla nebulización adulta",
  "Gafas nasales adultas",
  "Mascarilla oxígeno pediátrica",
  "Mascarilla monaghan pediátrica",
  "Mascarilla nebulización pediátrica",
  "Gafas nasales pediátricas",
  "Alargadera o2",
  "Contenedor agujas pequeño",
  "Contenedor agujas grande",
  "Gel hidroalcohólico",
  "Bolsas vómito",
  "Manta térmica",
  "Termómetro digital",
  "Termómetro infrarojos",
  "Esfingotensiómetro manual",
  "Manguitos esfingo manual: neonatal",
  "Manguitos esfingo manual: pediátrico",
  "Manguitos esfingo manual: adulto",
  "Manguitos esfingo manual: obeso",
  "Fonendoescopio adulto",
  "Linterna pupilar",
  "Tiras reactivas",
  "Lancetas",
  "Glucómetro",
  "Celulosa cortada",
  "Torniquete",
  "Tijeras cortaropa",
  "Bolsa hielo",
  "Bolsa calor",
  "Sutura cutania 100x6mm",
  "Sutura cutania 100x12mm",
  "Talla estéril",
  "Pinzas estériles",
  "Tijeras estériles",
  "Esparadrapo plástico 2,5",
  "Venda elástica",
  "Malla capelina cabeza",
  "Suero fisiológico 5ml",
  "Suero fisiológico 10ml",
  "Suero fisiológico 100ml",
  "Sueros de 100 ml",
  "Suero fisiológico 250 ml",
  "Clorhexidina 2%",
  "Venda crepe 4x7",
  "Venda crepe 10x10",
  "Venda gasa 10cm",
  "Venda cohesiva 10x10",
  "Gasas 20x20",
  "Gasas 40x40",
  "Aposito 7x2,5",
  "Aposito 10x8",
  "Aposito 20x8",
  "Cuña mujer",
  "Cuña hombre",
  "Guantes s",
  "Guantes m",
  "Guantes l",
  "Guantes xl",
  "Guantes estériles s",
  "Guantes estériles m",
  "Guantes estériles l",
  "Mantas un solo uso",
  "Sabanas un solo uso",
  "Bolsas objetos personalse sem pequeña",
  "Bolsas objetos personalse sem grandes",
  "Pilas aa",
  "Pilas aaa",
  "Pilas cr123",
  "Talonario sem",
  "Talonario Falck",
  "Desinfectante",
  "Desengrasante",
  "Papel wc",
  "Bobina papel",
  "Bayetas",
  "Estropajos",
  "Fregona",
  "Escobas",
  "Palos escoba-fregona",
  "Cubo fregar",
  "Recogedor",
  "Palos recogedor",
  "Escobilla wc",
  "Producto limpieza pulverizador tsu",
  "Bolsas escombreries negre",
  "Bolsas residuos gii",
  "Jabon platos",
  "Limpia cristales",
  "Pulsioximetre didal",
  "Gases 20x40",
  "Sueros 250 ml",
  "Llancetes (caixeta de 50)",
  "Faixa pèlvica",
  "Torniquet",
  "Iode",
  "Guedel número 2",
  "Pegats dea adult",
  "Pegats dea pediàtrics"
];
export const CRITICAL_KEYWORDS = [
  "torniquet",
  "faixa pèlvica",
  "pegats dea adult",
  "pegats dea pediàtrics",
  "parches schiller adulto",
  "parches schiller pediátrico"
];

// Material reservat al registre de Material supervisor.
export const SUPERVISOR_ONLY_MATERIALS = [
  "Cable ECG 4 derivadas",
  "Cable ECG 12 derivadas",
  "Sensor pulsioximetria adulto",
  "Manguito TA pediátrico Schiller",
  "Manguito TA adulto Schiller",
  "Manguito TA obeso schiller",
  "Tensiometro digital",
  "Tensiometro infrarojos",
  "Manguito tensiometro infantil",
  "Detector de monoxido",
  "Mascarilla Ambu 0",
  "Mascarilla Ambu 0A",
  "Mascarilla Ambu 2",
  "Mascarilla Ambu 3/4",
  "Mascarilla Ambu 5",
  "Mascarilla Ambu 6",
  "Termómetro digital",
  "Termómetro infrarojos",
  "Esfingotensiómetro manual",
  "Manguitos esfingo manual: pediátrico",
  "Manguitos esfingo manual: adulto",
  "Manguitos esfingo manual: obeso",
  "Manguitos esfingo manual: neonatal",
  "Fonendoescopio adulto",
  "Linterna pupilar",
  "Glucómetro",
  "Tijeras cortaropa",
  "Talonario FALCK",
  "Desengrasante",
  "Papel WC",
  "Bobina papel",
  "Bayetas",
  "Estropajos",
  "Fregona",
  "Escobas",
  "Palos Escoba-Fregona",
  "Cubo fregar",
  "Recogedor",
  "Palos Recogedor",
  "Escobilla WC",
  "BOLSAS ESCOMBRERIES NEGRE",
  "Producto limpieza pulverizador TSU",
  "jabon platos",
  "limpia cristales",
  "pulsioximetre didal",
  "desinfectante",
  "pilas cr123",
  "pilas aa",
  "pilas aaa"
];
