-- Correcciones administrativas auditables de consumos TSU/supervisor.
-- No borra el envio original: rectifica el total consolidado, el stock y el
-- pendiente de reposicion en una sola transaccion.
begin;

create table if not exists public.consumption_corrections (
  id bigint generated by default as identity primary key,
  incident_id uuid not null references public.incidents(id),
  lot text not null,
  zone text not null,
  warehouse_id text not null references public.warehouses(id),
  unit text not null,
  guard_code text not null,
  material text not null,
  previous_quantity integer not null check (previous_quantity >= 0),
  corrected_quantity integer not null check (corrected_quantity >= 0),
  stock_delta integer not null,
  reason text not null,
  actor_user_id uuid not null references auth.users(id),
  actor_role text not null,
  actor_zone text,
  created_at timestamptz not null default now()
);

create index if not exists consumption_corrections_incident_idx
  on public.consumption_corrections(incident_id, created_at desc);
create index if not exists consumption_corrections_scope_idx
  on public.consumption_corrections(lot, zone, created_at desc);

alter table public.consumption_corrections enable row level security;
revoke all on public.consumption_corrections from public, anon, authenticated;

drop policy if exists "Role based correction reads" on public.consumption_corrections;
create policy "Role based correction reads" on public.consumption_corrections
  for select to authenticated
  using (public.admin_can_access_zone(zone));

create or replace function public.correct_guard_consumption(
  p_incident_id uuid,
  p_lot text,
  p_material text,
  p_corrected_quantity integer,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_incident public.incidents%rowtype;
  v_warehouse_id text;
  v_zone text;
  v_role text;
  v_role_zone text;
  v_previous integer;
  v_stock_delta integer;
  v_materials jsonb;
  v_operation_id uuid := gen_random_uuid();
  v_correction_id bigint;
begin
  if auth.uid() is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  if p_incident_id is null or nullif(trim(p_material), '') is null then
    raise exception 'INVALID_CORRECTION';
  end if;
  if p_corrected_quantity is null or p_corrected_quantity < 0 or p_corrected_quantity > 2147483647 then
    raise exception 'INVALID_CORRECTED_QUANTITY';
  end if;
  if length(trim(coalesce(p_reason, ''))) < 5 then raise exception 'CORRECTION_REASON_REQUIRED'; end if;

  select role, zone into v_role, v_role_zone
  from public.admin_access_sessions
  where user_id = auth.uid() and expires_at > now();
  if v_role is null then raise exception 'ADMIN_ACCESS_REQUIRED'; end if;

  select * into v_incident
  from public.incidents
  where id = p_incident_id
  for update;
  if not found then raise exception 'INCIDENT_NOT_FOUND'; end if;
  -- Mientras la guardia sigue abierta, la corrección corresponde al propio
  -- dispositivo: allí se ve y se sustituye el total acumulado. Administración
  -- entra únicamente cuando ya no existe riesgo de un nuevo envío del turno.
  if now() < v_incident.occurred_at + interval '24 hours' then
    raise exception 'GUARD_STILL_ACTIVE';
  end if;

  select a.warehouse_id, w.zone
    into v_warehouse_id, v_zone
  from public.unit_warehouse_assignments a
  join public.warehouses w on w.id = a.warehouse_id
  where a.unit = v_incident.unit and w.lot = p_lot
  limit 1;
  if v_warehouse_id is null then raise exception 'UNIT_WAREHOUSE_NOT_CONFIGURED'; end if;
  if not public.admin_can_access_zone(v_zone) then raise exception 'ADMIN_ZONE_ACCESS_DENIED'; end if;

  perform pg_advisory_xact_lock(hashtextextended(v_warehouse_id || ':' || p_material, 1));
  v_previous := coalesce((v_incident.materials ->> p_material)::integer, 0);
  if v_previous = p_corrected_quantity then raise exception 'CORRECTION_WITHOUT_CHANGES'; end if;
  v_stock_delta := v_previous - p_corrected_quantity;

  if p_corrected_quantity = 0 then
    v_materials := coalesce(v_incident.materials, '{}'::jsonb) - p_material;
  else
    v_materials := jsonb_set(
      coalesce(v_incident.materials, '{}'::jsonb),
      array[p_material],
      to_jsonb(p_corrected_quantity),
      true
    );
  end if;

  update public.incidents
  set materials = v_materials, updated_at = now()
  where id = v_incident.id;

  update public.warehouse_inventory
  set quantity = quantity + v_stock_delta,
      pending_replenishment = greatest(0, pending_replenishment - v_stock_delta),
      updated_at = now()
  where warehouse_id = v_warehouse_id and material = p_material;
  if not found then raise exception 'INVENTORY_MATERIAL_NOT_FOUND'; end if;

  insert into public.stock_movements(
    warehouse_id, unit, guard_code, material, delta, movement_type,
    operation_id, performed_role, performed_zone
  ) values (
    v_warehouse_id, v_incident.unit, v_incident.incident_code, p_material,
    v_stock_delta, 'consumption_correction', v_operation_id, v_role, v_role_zone
  );

  insert into public.consumption_corrections(
    incident_id, lot, zone, warehouse_id, unit, guard_code, material,
    previous_quantity, corrected_quantity, stock_delta, reason,
    actor_user_id, actor_role, actor_zone
  ) values (
    v_incident.id, p_lot, v_zone, v_warehouse_id, v_incident.unit,
    v_incident.incident_code, p_material, v_previous, p_corrected_quantity,
    v_stock_delta, trim(p_reason), auth.uid(), v_role, v_role_zone
  ) returning id into v_correction_id;

  return jsonb_build_object(
    'correction_id', v_correction_id,
    'incident_id', v_incident.id,
    'unit', v_incident.unit,
    'guard_code', v_incident.incident_code,
    'material', p_material,
    'previous_quantity', v_previous,
    'corrected_quantity', p_corrected_quantity,
    'stock_delta', v_stock_delta,
    'warehouse_id', v_warehouse_id
  );
end;
$$;

revoke all on function public.correct_guard_consumption(uuid,text,text,integer,text)
  from public, anon;
grant execute on function public.correct_guard_consumption(uuid,text,text,integer,text)
  to authenticated;

commit;
